version: "3.9"
services:
  chat_api:
    build:
      context: .
      dockerfile: chat_api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./chat_api/.env
    depends_on:
      - data_service
      - embedding_worker

  data_service:
    build:
      context: .
      dockerfile: data_service/Dockerfile
    ports:
      - "8001:8000"

  embedding_worker:
    build:
      context: .
      dockerfile: embedding_worker/Dockerfile
    ports:
      - "8002:8000"
    env_file:
      - ./embedding_worker/.env 